version: '3'

services:
  server:
    build: .
    container_name: livraria_api
    restart: unless-stopped
    command: bash -c "npm install && npm run nodemon"
    networks:
      - livraria-network
    ports:
      - 3333:3333
    volumes:
      - .:/server
      - /server/node_modules
    links:
      - database
    depends_on:
      - database
      
  database:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: livraria_db
    restart: unless-stopped
    networks:
      - livraria-network
    environment:
      MYSQL_ROOT_PASSWORD: thadeu12
      MYSQL_DATABASE: livraria
    ports:
      - 3308:3306
    expose:
      - 3308
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    logging:
      driver: none
      
volumes:
  data:
    driver: local

networks:
  livraria-network:
    name: livraria-network